"""Tests for :mod:`sisr.ssim` — the daala-methodology SSIM port.

Two layers of evidence, mirroring ``tests/test_imresize.py``:

1. Structural tests (always run) pin the properties that make this a daala
   port rather than "SSIM with a different sigma": the integer kernel summing
   to 256, its 9-tap support at sigma 1.5, and the height-only sigma.
2. Numeric parity against values generated by the real daala C reference
   (``tests/reference/daala_ssim.c``), committed to the repo so this needs no
   compiler.
"""

import json
from pathlib import Path

import pytest

from tests.reference.daala_ssim_cases import CASES, make_planes

EXPECTED_PATH = Path(__file__).resolve().parent / "reference" / "daala_ssim_expected.json"
EXPECTED: dict[str, float] = json.loads(EXPECTED_PATH.read_text(encoding="utf-8"))


def test_reference_expectations_cover_every_case():
    """The committed C output must cover the whole case matrix, in range."""
    assert set(EXPECTED) == {c["name"] for c in CASES}
    assert all(0.0 < v <= 1.0 for v in EXPECTED.values()), EXPECTED


def test_reference_identical_planes_score_one():
    assert EXPECTED["identical_128x128"] == pytest.approx(1.0, abs=1e-15)


def test_reference_sigma_depends_on_height_not_content():
    """Same content, transposed shape -> different sigma -> different score.

    Guards the vendoring: if daala's `_h*(1.5/256)` were mis-transcribed as a
    constant, these two would be equal.
    """
    assert EXPECTED["landscape_200x320"] != EXPECTED["portrait_320x200"]


def test_case_planes_are_deterministic():
    """make_planes must be reproducible, or the committed values are meaningless."""
    for case in CASES:
        a1, b1 = make_planes(case)
        a2, b2 = make_planes(case)
        assert (a1 == a2).all() and (b1 == b2).all(), case["name"]
