"""Tests for :mod:`sisr.ssim` — the daala-methodology SSIM port.

Two layers of evidence, mirroring ``tests/test_imresize.py``:

1. Structural tests (always run) pin the properties that make this a daala
   port rather than "SSIM with a different sigma": the integer kernel summing
   to 256, its 9-tap support at sigma 1.5, and the height-only sigma.
2. Numeric parity against values generated by the real daala C reference
   (``tests/reference/daala_ssim.c``), committed to the repo so this needs no
   compiler.
"""

import json
from pathlib import Path

import numpy as np
import pytest
import torch

from sisr.ssim import _gaussian_kernel_int, daala_ssim, quantize_u8
from tests.reference.daala_ssim_cases import (
    CASES,
    REAL_SETS,
    discover_real_cases,
    make_planes,
    make_real_planes,
)

EXPECTED_PATH = Path(__file__).resolve().parent / "reference" / "daala_ssim_expected.json"
EXPECTED: dict[str, float] = json.loads(EXPECTED_PATH.read_text(encoding="utf-8"))
DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def test_reference_expectations_cover_every_case():
    """The committed C output must cover the whole synthetic case matrix, in range.

    Not an equality check against ``set(EXPECTED)``: the committed JSON also
    holds 119 real-image cases (see ``test_real_image_matches_daala_c_reference``
    below), which stay in the file regardless of whether ``data/`` exists on
    the machine currently running the suite. That subset check alone would miss
    a stray, orphaned, or misspelled key anywhere in the 133-entry file -- the
    only structural check on the JSON on a data-less machine (i.e. CI) -- so
    every key that isn't a synthetic case name is additionally required to look
    like a real-image key: ``<set>/<stem>`` with ``<set>`` one of
    :data:`~tests.reference.daala_ssim_cases.REAL_SETS`.
    """
    synthetic_names = {c["name"] for c in CASES}
    assert synthetic_names <= set(EXPECTED)
    unrecognized = {
        key for key in set(EXPECTED) - synthetic_names if key.split("/", 1)[0] not in REAL_SETS
    }
    assert not unrecognized, (
        f"key(s) in {EXPECTED_PATH.name} are neither a synthetic case nor a "
        f"'<set>/<stem>' real-image case with <set> in {sorted(REAL_SETS)}: {sorted(unrecognized)}"
    )
    assert all(0.0 < v <= 1.0 for v in EXPECTED.values()), EXPECTED


def test_reference_identical_planes_score_one():
    assert EXPECTED["identical_128x128"] == pytest.approx(1.0, abs=1e-15)


def test_reference_sigma_depends_on_height_not_content():
    """Same content, transposed shape -> different sigma -> different score.

    Guards the vendoring: if daala's `_h*(1.5/256)` were mis-transcribed as a
    constant, these two would be equal.
    """
    assert EXPECTED["landscape_200x320"] != EXPECTED["portrait_320x200"]


def test_case_planes_are_deterministic():
    """make_planes must be reproducible, or the committed values are meaningless."""
    for case in CASES:
        a1, b1 = make_planes(case)
        a2, b2 = make_planes(case)
        assert (a1 == a2).all() and (b1 == b2).all(), case["name"]


def test_kernel_golden_vector_at_sigma_1_5():
    """Hand-computed from daala's gaussian_filter_init at sigma=1.5 (H=256).

    Taps are `int(256*scale*exp(-0.5*ci^2/sigma^2) + 0.5)` and the centre is
    `256 - 2*sum(sides)`, so the kernel sums to exactly 256 by construction.
    """
    assert _gaussian_kernel_int(1.5, 256) == [2, 9, 28, 55, 68, 55, 28, 9, 2]


def test_kernel_sums_to_kernel_weight():
    for sigma in (0.5, 1.5, 3.0, 7.25):
        assert sum(_gaussian_kernel_int(sigma, 4096)) == 256


def test_kernel_support_is_nine_not_eleven_at_sigma_1_5():
    """daala never reduces to Wang. At sigma=1.5 Wang uses 11 taps; daala's
    truncation rule (`error in the first truncated coefficient <= 0.5/256`)
    gives 9. A "fix" toward 11 would silently stop being a daala port."""
    assert len(_gaussian_kernel_int(1.5, 256)) == 9


def test_kernel_length_follows_daala_truncation_rule():
    """Support comes from daala's truncation-error rule, not a 3-sigma cutoff.

    At sigma=3.0 (a 512-tall image) the rule gives kernel_len=8 -> 17 taps,
    where the plausible-looking `floor(3*sigma)` would give 9 -> 19. This is the
    ONLY test that distinguishes the two: at sigma=1.5 both yield 4, so the
    golden vector and the sum invariant both pass under the wrong rule.
    """
    assert len(_gaussian_kernel_int(3.0, 512)) == 17


def test_kernel_max_len_cap():
    """`kernel_len` is capped at `max_len - 1`, so a narrow plane truncates."""
    assert len(_gaussian_kernel_int(3.0, 4)) == 7  # kernel_len = 3 -> 2*3+1


def test_kernel_degenerates_to_single_tap():
    """A tiny sigma drives `len` to 0: one tap carrying the whole weight."""
    assert _gaussian_kernel_int(8 * (1.5 / 256), 8) == [256]


def _as_batch(plane: np.ndarray) -> torch.Tensor:
    """uint8 (H, W) -> (1, 1, H, W) float32 in [0, 1], the metric path's shape."""
    return torch.from_numpy(plane.astype(np.float32) / 255.0)[None, None]


@pytest.mark.parametrize("case", CASES, ids=lambda c: c["name"])
def test_matches_daala_c_reference(case):
    """Parity with the real daala C at rel=1e-9.

    Not bit-equality: only the final pooling summation order differs (the C
    accumulates sequentially row-major, torch reduces as a tree). That
    divergence grows with plane size (~eps*n/4): a *correct* port already
    exceeds 1e-12 on flat content at 256^2 (1.494e-12) and reaches 1.545e-11 at
    1024^2, so 1e-12 is too tight to survive resolution growth. Real defects,
    by measurement, are >= 4.96e-8 (the faintest, a float32 leak; every
    structural error was >= 1e-1). 1e-9 sits mid-band: ~60x above the
    summation-order noise ceiling, ~50x below the faintest real defect.
    Thread count (1-16) only moves the last ulp, so this is deterministic
    C-side summation-order error, not platform flakiness.
    """
    a, b = make_planes(case)
    got = daala_ssim(_as_batch(a), _as_batch(b)).item()
    assert got == pytest.approx(EXPECTED[case["name"]], rel=1e-9)


def _real_case_params() -> list:
    """Build the ``case`` parametrize argument for the real-image parity test.

    Mirrors ``tests/test_imresize.py``'s real-data pattern (see
    ``REFERENCE_DIR`` and its skip logic): a directory-existence check
    producing a single cleanly-skipped node whose reason names what is
    missing, versus the directory existing but yielding no cases.

    That second condition is *not* asserted here. This function runs inside
    the ``@pytest.mark.parametrize(...)`` decorator expression, i.e. at
    collection time -- an ``assert`` that fires here raises during collection
    of this whole module, which pytest reports as an interrupted session
    (``Interrupted: 1 error during collection``), aborting every test in the
    run, not just this file. That's a real, ordinary failure mode: ``data/``
    can exist (other tests need it) while none of Set5/Set14/BSD100 do (a
    partial download). So an empty-but-present directory instead produces one
    parametrized node carrying ``case=None``; the loud failure happens in the
    test body below, which only fails that one node.
    """
    if not DATA_DIR.is_dir():
        reason = (
            f"{DATA_DIR} not present -- fetch Set5/Set14/BSD100 HR image sets (see "
            "tests/reference/daala_ssim_cases.py REAL_SETS) to enable real-image daala "
            "SSIM parity."
        )
        return [pytest.param(None, marks=pytest.mark.skip(reason=reason), id="no-data")]
    cases = discover_real_cases()
    if not cases:
        return [pytest.param(None, id="no-cases")]
    return [pytest.param(c, id=c["name"]) for c in cases]


@pytest.mark.parametrize("case", _real_case_params())
def test_real_image_matches_daala_c_reference(case):
    """Real Set5/Set14/BSD100 bicubic-baseline parity against the daala C.

    Same rel=1e-9 bound as :func:`test_matches_daala_c_reference` and for the
    same reason -- pooling summation-order divergence, not a defect; see that
    test's docstring for the full measured bracket. The bicubic baseline
    (:func:`~tests.reference.daala_ssim_cases.make_real_planes`) needs no
    trained checkpoint, so these 119 expected values stay regenerable and
    meaningful indefinitely.

    ``case is None`` only reaches here for the "``data/`` exists but yielded no
    cases" node (see :func:`_real_case_params`) -- the "``data/`` absent" node
    carries the same sentinel but is skip-marked, so its body never runs.
    """
    if case is None:
        pytest.fail(f"{DATA_DIR} exists but yielded no real-image daala SSIM cases")
    bicubic, hr = make_real_planes(case)
    got = daala_ssim(_as_batch(bicubic), _as_batch(hr)).item()
    assert got == pytest.approx(EXPECTED[case["name"]], rel=1e-9)


def test_identical_inputs_score_one():
    """x vs x scores exactly 1 -- but that assertion alone can never fail.

    With x == y, every numerator factor is bit-identical to its denominator
    counterpart except for one extra factor of `mw`, so the per-pixel ratio
    (before pooling) reduces to `mw` itself for ANY kernel and ANY weight
    field; pooling `mw` over `sum(mw)` is then 1 regardless. Empirically
    confirmed unchanged with sigma pinned to 1.5, 0.1, or 40.0, the `max_len`
    cap inverted, and `mw` pinned to 65536 or to the nonsense constant 1.0. So
    this test also flips one pixel: only a perturbed pair exercises the kernel
    and the pooling weights enough to be able to fail.
    """
    x = _as_batch(make_planes(CASES[0])[0])
    assert daala_ssim(x, x).item() == pytest.approx(1.0, abs=1e-12)

    y = x.clone()
    cy, cx = y.shape[-2] // 2, y.shape[-1] // 2
    y[0, 0, cy, cx] = 1.0 - y[0, 0, cy, cx]
    got = daala_ssim(x, y).item()
    assert got < 1.0
    # One flipped pixel out of 65536, diluted by the 9-tap kernel and pooled
    # over the whole plane -- a small, specific drop, not "some smaller number".
    assert got == pytest.approx(0.9999930105825837, rel=1e-9)


def test_multichannel_is_mean_over_planes():
    a, b = make_planes(CASES[0])
    c, d = make_planes(CASES[1])
    # Same H so the kernel matches; stack two independent plane pairs as channels.
    c, d = c[:256, :256], d[:256, :256]
    per_plane = [
        daala_ssim(_as_batch(a), _as_batch(b)).item(),
        daala_ssim(_as_batch(c), _as_batch(d)).item(),
    ]
    stacked_sr = torch.cat([_as_batch(a), _as_batch(c)], dim=1)
    stacked_hr = torch.cat([_as_batch(b), _as_batch(d)], dim=1)
    got = daala_ssim(stacked_sr, stacked_hr).item()
    assert got == pytest.approx(sum(per_plane) / 2, rel=1e-12)


def test_batch_and_channel_reduce_consistently():
    """B > 1 *together with* C > 1 is needed to guard the ``reshape`` ->
    ``view(b, c)`` pipeline against a desync between ``sr``'s and ``hr``'s
    plane order.

    Note on scope: the final ``per_plane.view(b, c).mean(dim=1).mean()`` step
    is a nested arithmetic mean over a full, equal-sized (b, c) partition --
    that is *always* equal to the grand mean of all b*c planes, for *any*
    grouping of the same b*c elements (confirmed by swapping it to
    ``view(c, b)`` directly: differs only by float noise, ~1e-16 relative, not
    by a meaningful amount). So no test on the *output*
    can catch a transposed final view. What a B>1,C>1 test *can* catch is
    ``sr`` and ``hr`` being flattened to mismatched (batch, channel) order
    before that point -- e.g. one of them transposed relative to the other --
    which silently compares the wrong plane pairs. With B=1 or C=1 (as in the
    two tests above) that desync is a no-op, since there is only one row or
    one column to begin with; confirmed by running the mismatch below through
    both of them and finding it invisible there. Six independent
    single-channel pairs are cropped to a common 64x64 and stacked as two
    3-channel batch entries; the batched call must equal the mean of the two
    per-entry (mean-over-channel) scores computed independently.
    """
    names = [
        "noise_256x256",
        "noise_512x512",
        "landscape_200x320",
        "portrait_320x200",
        "blurred_320x480",
        "constant_offset_64x64",
    ]
    crop = 64
    planes = {}
    for case in CASES:
        if case["name"] in names:
            a, b = make_planes(case)
            planes[case["name"]] = (a[:crop, :crop], b[:crop, :crop])

    def stack_channels(*case_names: str) -> tuple[torch.Tensor, torch.Tensor]:
        srs, hrs = zip(*(planes[n] for n in case_names), strict=True)
        sr = torch.cat([_as_batch(p) for p in srs], dim=1)
        hr = torch.cat([_as_batch(p) for p in hrs], dim=1)
        return sr, hr

    sample0_sr, sample0_hr = stack_channels(*names[:3])
    sample1_sr, sample1_hr = stack_channels(*names[3:])
    per_sample = [
        daala_ssim(sample0_sr, sample0_hr).item(),
        daala_ssim(sample1_sr, sample1_hr).item(),
    ]

    batched_sr = torch.cat([sample0_sr, sample1_sr], dim=0)
    batched_hr = torch.cat([sample0_hr, sample1_hr], dim=0)
    got = daala_ssim(batched_sr, batched_hr).item()
    assert got == pytest.approx(sum(per_sample) / 2, rel=1e-12)


def test_quantize_roundtrips_every_8bit_level():
    """Every 8-bit level must survive the round trip exactly.

    This is the property the pipeline depends on: studio-range Y derives from
    uint8 sources, and an off-by-one or a wrong scale here would shift every
    daala score. Robust to float representation, unlike a tie test.
    """
    levels = torch.arange(256, dtype=torch.float64) / 255.0
    got = quantize_u8(levels.view(1, 1, 1, 256))
    assert got.flatten().tolist() == list(range(256))


def test_quantize_rounds_half_away_from_zero():
    """Ties go away from zero, not to even — sisr.imresize's convention.

    The precondition assert matters: k/255 is never exactly representable
    (255 = 3*5*17 has no power-of-two factor), so the test verifies that the
    scaled value really does land on a tie before asserting how it breaks.
    Without it, a representation change would silently make this test vacuous.
    """
    x = torch.tensor([[[[2.5 / 255]]]], dtype=torch.float64)
    assert (x * 255.0).item() == 2.5, "precondition: scaled value must be exactly a tie"
    # half-away-from-zero -> 3; torch.round's ties-to-even would give 2.
    assert quantize_u8(x).item() == 3.0


def test_quantize_clamps_out_of_range():
    t = torch.tensor([[[[-0.5, 1.5]]]])
    assert quantize_u8(t).flatten().tolist() == [0.0, 255.0]


def test_rejects_mismatched_shapes():
    with pytest.raises(ValueError, match="same shape"):
        daala_ssim(torch.zeros(1, 1, 8, 8), torch.zeros(1, 1, 8, 9))


def test_rejects_non_4d_input():
    """A 3-D input must name the rank problem, not leak the ``b, c, h, w =
    sr.shape`` tuple-unpack's ``ValueError: not enough values to unpack``."""
    with pytest.raises(ValueError, match="4-D"):
        daala_ssim(torch.zeros(1, 8, 8), torch.zeros(1, 8, 8))


requires_cuda = pytest.mark.skipif(not torch.cuda.is_available(), reason="needs a CUDA device")


@requires_cuda
@pytest.mark.parametrize("case", CASES, ids=lambda c: c["name"])
def test_matches_cpu_on_cuda(case):
    """float64 conv on CUDA must reproduce the CPU integer-accumulation result.

    The kernel is placed on ``sr.device``, so in the real pipeline this runs
    float64 convolution on CUDA. cuDNN accepts ``kDouble`` and its algorithm
    search includes FFT-based convolution, which would not produce exact
    integers -- the assumption the whole port rests on -- and every other test
    in this file runs on CPU only, so this path was previously unexercised.

    Measured on an RTX 5060: 9 of the 14 cases are bit-identical CPU vs CUDA;
    the other 5 (``landscape_200x320``, ``odd_101x67``, ``tiny_8x8``,
    ``constant_offset_64x64``, ``noise_snr_low_256x256``) differ by at most
    3.16e-16 relative -- a single float64 ulp, consistent with cuDNN choosing a
    different but still-exact summation order for the final convolution
    reduction, not FFT-based lossy accumulation. Not asserted as exact
    equality, since it measurably isn't; rel=1e-12 is ~3e5x above that noise.
    """
    a, b = make_planes(case)
    x_cpu, y_cpu = _as_batch(a), _as_batch(b)
    x_cuda, y_cuda = x_cpu.cuda(), y_cpu.cuda()
    cpu = daala_ssim(x_cpu, y_cpu).item()
    cuda = daala_ssim(x_cuda, y_cuda).item()
    assert cuda == pytest.approx(cpu, rel=1e-12)
