"""Tests for :mod:`sisr.ssim` — the daala-methodology SSIM port.

Two layers of evidence, mirroring ``tests/test_imresize.py``:

1. Structural tests (always run) pin the properties that make this a daala
   port rather than "SSIM with a different sigma": the integer kernel summing
   to 256, its 9-tap support at sigma 1.5, and the height-only sigma.
2. Numeric parity against values generated by the real daala C reference
   (``tests/reference/daala_ssim.c``), committed to the repo so this needs no
   compiler.
"""

import json
from pathlib import Path

import pytest

from sisr.ssim import _gaussian_kernel_int
from tests.reference.daala_ssim_cases import CASES, make_planes

EXPECTED_PATH = Path(__file__).resolve().parent / "reference" / "daala_ssim_expected.json"
EXPECTED: dict[str, float] = json.loads(EXPECTED_PATH.read_text(encoding="utf-8"))


def test_reference_expectations_cover_every_case():
    """The committed C output must cover the whole case matrix, in range."""
    assert set(EXPECTED) == {c["name"] for c in CASES}
    assert all(0.0 < v <= 1.0 for v in EXPECTED.values()), EXPECTED


def test_reference_identical_planes_score_one():
    assert EXPECTED["identical_128x128"] == pytest.approx(1.0, abs=1e-15)


def test_reference_sigma_depends_on_height_not_content():
    """Same content, transposed shape -> different sigma -> different score.

    Guards the vendoring: if daala's `_h*(1.5/256)` were mis-transcribed as a
    constant, these two would be equal.
    """
    assert EXPECTED["landscape_200x320"] != EXPECTED["portrait_320x200"]


def test_case_planes_are_deterministic():
    """make_planes must be reproducible, or the committed values are meaningless."""
    for case in CASES:
        a1, b1 = make_planes(case)
        a2, b2 = make_planes(case)
        assert (a1 == a2).all() and (b1 == b2).all(), case["name"]


def test_kernel_golden_vector_at_sigma_1_5():
    """Hand-computed from daala's gaussian_filter_init at sigma=1.5 (H=256).

    Taps are `int(256*scale*exp(-0.5*ci^2/sigma^2) + 0.5)` and the centre is
    `256 - 2*sum(sides)`, so the kernel sums to exactly 256 by construction.
    """
    assert _gaussian_kernel_int(1.5, 256) == [2, 9, 28, 55, 68, 55, 28, 9, 2]


def test_kernel_sums_to_kernel_weight():
    for sigma in (0.5, 1.5, 3.0, 7.25):
        assert sum(_gaussian_kernel_int(sigma, 4096)) == 256


def test_kernel_support_is_nine_not_eleven_at_sigma_1_5():
    """daala never reduces to Wang. At sigma=1.5 Wang uses 11 taps; daala's
    truncation rule (`error in the first truncated coefficient <= 0.5/256`)
    gives 9. A "fix" toward 11 would silently stop being a daala port."""
    assert len(_gaussian_kernel_int(1.5, 256)) == 9


def test_kernel_length_follows_daala_truncation_rule():
    """Support comes from daala's truncation-error rule, not a 3-sigma cutoff.

    At sigma=3.0 (a 512-tall image) the rule gives kernel_len=8 -> 17 taps,
    where the plausible-looking `floor(3*sigma)` would give 9 -> 19. This is the
    ONLY test that distinguishes the two: at sigma=1.5 both yield 4, so the
    golden vector and the sum invariant both pass under the wrong rule.
    """
    assert len(_gaussian_kernel_int(3.0, 512)) == 17


def test_kernel_max_len_cap():
    """`kernel_len` is capped at `max_len - 1`, so a narrow plane truncates."""
    assert len(_gaussian_kernel_int(3.0, 4)) == 7  # kernel_len = 3 -> 2*3+1


def test_kernel_degenerates_to_single_tap():
    """A tiny sigma drives `len` to 0: one tap carrying the whole weight."""
    assert _gaussian_kernel_int(8 * (1.5 / 256), 8) == [256]
